quiet: False

packages:
  github.com/Cealgull/Middleware/internal/ipfs:
    interfaces:
      IPFSStorage:
        config:
          filename: "mock_{{.InterfaceName}}.go"
          dir: "{{.InterfaceDir}}/mocks"
          with-expecter: True
          outpkg: mocks
  github.com/Cealgull/Middleware/internal/fabric/common:
    config:
      filename: "mock_{{.InterfaceName}}.go"
      dir: "{{.InterfaceDir}}/mocks"
      with-expecter: True
      unroll-variadic: True
      outpkg: mocks
    interfaces:
      Network:
